### ISSUE TITLE
Problem parsing content from medium.com

### ISSUE THREAD

**Issue by boncey** [cantino/ruby-readability#62]
I've found that ruby-readability seems to have problems with a couple of blog posts on Medium seem (it may be more, I've only tested two).

https://medium.com/our-addictions/ae81e19b0289 & https://medium.com/on-product-management/926ab5c39156.

ruby-readability seems to see the various paragraphs (divided by `<hr class="section-divider">` as separate sections and then it picks the one with the highest score.

```
readability --debug https://medium.com/our-addictions/ae81e19b0289
Top 5 candidates:
 Candidate div#.section-inner layout-single-column with score 45.0
 Candidate div#.section-inner layout-single-column with score 42.0
 Candidate div#.section-inner layout-single-column with score 42.0
 Candidate div#.section-inner layout-single-column with score 40.0
 Candidate div#.section-inner layout-single-column with score 37.0
 Best candidate div#.section-inner layout-single-column with score 45.0
```

It then just shows the text from what looks like the longest paragraph.

Is there likely to be an easy fix for things like this - or some way of working around it for specific sites?
Instapaper used to have a custom parser with user-contributed rules (although it seems to have gone away since it was sold). Have there been any thoughts about doing that sort of thing for ruby-readability at all?

Thanks, Darren.

**Comment by kovson** [comment]
Problem still exists, are there any possible solutions?

**Comment by cantino** [comment]
I'm not actively using this library anymore and so aren't working on further development.  I'm very open to pull requests and improvements, however, and would happily add another maintainer if someone wants to get involved and push it forward.
