### ISSUE TITLE
New Rubygems release?

### ISSUE THREAD

**Issue by andyw8** [cantino/ruby-readability#83]
:wave: Hi @cantino @olleolleolle 

I realise this an old gem, but I see you've made commits or merged PRs within the past year or so.

The last Rubygems release was in 2014 – do you think it would be feasible to make a new release any time soon?

Thanks

**Comment by cantino** [comment]
Hey @andyw8. The last meaningful change was in 2014. The more recent commit was just dropping an unused gemspec property.

**Comment by andyw8** [comment]
Thanks
