### ISSUE TITLE
CI build failures

### ISSUE THREAD

**Issue by olleolleolle** [cantino/ruby-readability#84]
One of the failures is about do_not_allow not being accessible in an RSpec  ExampleGroup. Is that outside an "it"? Well, it fails.

Perhaps, as an update, the matrix of Ruby versions to run in CI could be updated, too!

**Comment by andyw8** [comment]
I just started looking into this, and noticed there's no mention of `load_image` anywhere else in the code. It was renamed to `get_image_size` in 6fa12bbf1ab08168e22bf6a7ca104adb63fbef45.

**Comment by olleolleolle** [comment]
@andyw8  Thanks!

:hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:
